name: example
description: FAB Circular Menu+ Example
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fab_circular_menu_plus:
    path: ../

dev_dependencies:
  analyzer: ^6.3.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
